language: php
php:
  - 5.6
  
sudo: false

before_script:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpcs --standard=PSR2 src/ tests/
  - vendor/bin/phpunit -c phpunit.xml
